baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Byte Bard Software'
theme = "hermit-v2"


[params.author]
  name = "Borja Lorente"

[taxonomies]
  tags = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "This is the desxcription of a site."
  # images = [""]
  themeColor = "#FFFFFF"

  homeSubtitle = "Crafting delightful, playful software."
  #footerCopyright = "CHANGE ME FOOTER COPYRIGHT"
  gitUrl = "https://github.com/blorente/blog"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = ""
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  tagSymbol = "#"
  pinned = "Pinned Posts"
  descriptionInPosts= true
  # initialPublish = "Initally Posted on: "

  [[params.socialLinks]]
    name = "x"
    url = "https://twitter.com/BLorenteEs"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/blorente"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 10
