baseURL = 'https://bytebard.software/'
languageCode = 'en-us'
title = 'Byte Bard Software'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Articles'
pageRef = '/articles'
weight = 20

[[menus.main]]
name = 'About Us'
pageRef = '/about'
weight = 30
